version: '3'
services:
  php:
    image: laravelsail/php82-composer
    volumes:
      - './:/app'
    working_dir: /app
    user: '1000:1000'
    ports:
      - '7000:8000'
    command: php -S 0.0.0.0:8000 -t /app
